### ISSUE TITLE
Windows SmartScreen blocks Aurous installation

### ISSUE THREAD

**Issue by fruitwasp** [AurousGroup/Bug-Tracker#116]
Windows SmartScreen notifies the user the install is blocked.

![](http://i.imgur.com/9ZqtvT3.png)

Clicking on the More Info button let's the user install it anyway.

![](http://i.imgur.com/9sv2ooj.png)

Any way you can get around this?

**Comment by Codeusa** [comment]
Are you using the latest msi from the website? We have signed it so this shouldn't occur

**Comment by fruitwasp** [comment]
Yes, I have. Downloaded the latest msi about 20 minutes ago.

**Comment by ramses2029** [comment]
The same here.

**Comment by NoShotz** [comment]
i generally expect this with new version of new software, so i just let it
through smartscreen filter

**Comment by fruitwasp** [comment]
I've noticed this is resolved.
