### ISSUE TITLE
Search results get back in gibberish

### ISSUE THREAD

**Issue by Draxler** [AurousGroup/Bug-Tracker#125]
When i put search term JAZZ into search box, i get back results in gibberish.
It seams Aurous can't recognise a lot of ''foraign'' characters and start showing characters at random.

![jazz](https://cloud.githubusercontent.com/assets/7681671/10438938/f138664a-7136-11e5-9f2a-eacfb2cfebc0.PNG)

**Comment by Codeusa** [comment]
Assigning to @dmxt because this is a font issue.

**Comment by dmxt** [comment]
Encoding related. Not my assignment. 

Andrew confirmed that it's fixed, it should be patched soon.

**Comment by Codeusa** [comment]
Fixed

![fixed](http://i.andrew.im/0gnw8i.png)

**Comment by Draxler** [comment]
@Codeusa 

is fix pushed becuase i don't see any changes on my side?

**Comment by anVlad11** [comment]
@Draxler @Codeusa can confirm, non-latin characters still looking weird.
