### ISSUE TITLE
XSS/HTML possible in username

### ISSUE THREAD

**Issue by xBytez** [AurousGroup/Bug-Tracker#126]
Hey there. I just found out I can use HTML in my Aurous username, you might want to fix this. :+1: 

![](https://xbytez.eu/i/d/2015-10-13_01-23-52.png)

**Comment by Codeusa** [comment]
Aurous is a local HTML5 app, XSS would imply a remote site was able to execute Javascript on your device without your permission which is not possible. As the username is meant to be styleable we allow it to be appended as HTML.

Aurous plugin system is entirely html5/javscript based and relies on the ability to execute Javascript. So  this falls under wontfix/
