### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by abrevet** [AurousGroup/Bug-Tracker#136]
When application for mobile !!!!! :-)

**Comment by NoShotz** [comment]
pretty sure this isnt a bug, and there will be one eventually

**Comment by Mikaela** [comment]
This would be feature, but could also be bug based on the fact that at least Android, Saifish, Windows Phone and iOS clients have been promised at Twitter.

**Comment by NoShotz** [comment]
how would it be a bug if an IOS/Andriod app doesnt even exist yet, but will be coming

**Comment by Mikaela** [comment]
Unfullfilled promise can be intercepted as a bug. In case you don't understand, I will just stop this discussion as it doesn't add any worth to the issue.

**Comment by Mikaela** [comment]
Unfullfilled promise can be intercepted as a bug. In case you don't understand, I will just stop this discussion as it doesn't add any worth to the issue.

**Comment by NoShotz** [comment]
the program just came out in alpha two days ago, why would you expect a promise to be fullfilled within two days of an alpha release
