### ISSUE TITLE
Aurous won't open after last update / Win 7 / 

### ISSUE THREAD

**Issue by Draxler** [AurousGroup/Bug-Tracker#151]
After latest update Aurous won't open. It's like nothing happened. Not even in system manager is not visible that Aurous get activated at all. After you click on Aurous icon i get litlle window which ask me for permission to open Aurous and when i click Yes , nothing happened after that. 

UPDATE:

I uninstalled Aurous completley, then install it again. Aurous would open only for the first time, after it closes, Aurous won't open again no mether what.

**Comment by jimbill88** [comment]
Exact same problem, minus asking for permissions.
Aurous opens when prompted on install, then will not open on subsequent attempts.
Running on Win8 machine.
Previous version (prior to update at 5pm MST 10/14/15) would open and play songs, but not save to profile. Newest ability was save songs to profile list, then problem appeared.
Will run after uninstall and reinstall.
Cleared .db files and song files in music folders, but problem remains.

**Comment by Codeusa** [comment]
You will need to reinstall it, we bricked the bootstrapper.

**Comment by duramato** [comment]
@Codeusa I've also had that problem ,do I use which version ? aurous.me or mega?

**Comment by jimbill88** [comment]
Thanks Codeusa. Solved.

**Comment by Codeusa** [comment]
@duramato they're both the same.

**Comment by duramato** [comment]
@Codeusa Just unistalled and resinstalled and still doesnt work.
If i look at the task manager it starts but after a few it just disapears .It just doesnt start any clue?

**Comment by Draxler** [comment]
After complete uninstall of Aurous app and deletion of all leftovers and then fresh install of latest Aurous, this issue was gone (Win 7 OS).
