### ISSUE TITLE
Dropping files into playlist

### ISSUE THREAD

**Issue by ElGatoSaez** [AurousGroup/Bug-Tracker#164]
Can't drop files into playlist, got this. Maybe should be a feature in next versions? 
![image](https://cloud.githubusercontent.com/assets/10396037/10502670/d448d044-72c4-11e5-8989-724832f42fc5.png)

**Comment by NoShotz** [comment]
Probably wouldnt be easy to do, as the program is HTML/CSS based and uses a web rendering engine to render it, and when you drag and drop a file onto a web browser / rendering engine, it will change the "website" address to the files path

**Comment by ElGatoSaez** [comment]
The dropping can work as dropping files to an eMail

**Comment by dmxt** [comment]
Currently drag & drop feature isn't implemented, hopefully in the future we'll implement it.
