### ISSUE TITLE
Access denied when adding to collection

### ISSUE THREAD

**Issue by esmithcarepoint** [AurousGroup/Bug-Tracker#170]
When searching in Discover and attempting to (download/add to collection) I receive this error only after downloading one song first. Subsequent attempts to download produce
the same error but the song does download to the directory I have specified. 
I do not see an entry being populated in the debug.log if that helps. Also, I have the application set to run as local admin on a windows 10 PC. I am not clicking the play button first and pressing the +, I am just clicking "next" to the play button in the surrounding space that changes the cursor.

```
java.io.IOException: Access is denied.

	at sun.nio.fs.WindowsWatchService$Poller.implRegister(WindowsWatchService.java:407)
	at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260)
	at sun.nio.fs.WindowsWatchService$Poller.run(WindowsWatchService.java:533)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by garretteleniak** [comment]
Do you have proper ownership or permissions for the first folder entry in the advanced settings?

**Comment by esmithcarepoint** [comment]
Yes, I am the current owner of the folder. I have also given "Everyone" full control under the folder's security settings,

**Comment by esmithcarepoint** [comment]
Seems like Aurous got the ban-hammer, sorry to hear dudes. For the sake of cleaning out tickets, I'm closing mine.
