### ISSUE TITLE
The repeat button doesn't work.

### ISSUE THREAD

**Issue by robochicken11** [AurousGroup/Bug-Tracker#173]
Only plays the song once

**Comment by esmithcarepoint** [comment]
I've had the same problem as well as the shuffle not working (windows msi installer, windows 10 os)

**Comment by NoShotz** [comment]
Both of the buttons do not function yet

**Comment by dmxt** [comment]
Both buttons don't function, in the future they will.

**Comment by G07cha** [comment]
@dmxt, why you are closing issue? This is still a problem so it can be marked as feature and still be presented in list of opened issues.
