### ISSUE TITLE
Missing album's illustration in Album description

### ISSUE THREAD

**Issue by FXlife** [AurousGroup/Bug-Tracker#179]
When I go to My Collections > Albums, I select an album in my collection (the album has an illustration) but the album's illustration is not shown

![sans titre](https://cloud.githubusercontent.com/assets/15075923/10529809/a28bbcb6-7390-11e5-8f1f-aba26663ea2d.png)

**Comment by dmxt** [comment]
I'll implement this feature in the future. Thanks for the suggestion.
