### ISSUE TITLE
Previous page by pressing <DEL> is a blank page

### ISSUE THREAD

**Issue by soyuka** [AurousGroup/Bug-Tracker#25]
I could not get out of the web page after clicking the web link:

![screen shot 2015-10-10 at 18 00 27](https://cloud.githubusercontent.com/assets/1321971/10412005/d48b1bba-6f78-11e5-88c2-9f420a1a0838.png)

Naturally I typed `Delete` to go back. 

If you press the key twice you're on a blank screen :

![screen shot 2015-10-10 at 18 02 03](https://cloud.githubusercontent.com/assets/1321971/10412011/09e9a768-6f79-11e5-8c7b-12d696f8b8d1.png)

`Shift+Delete` goes to previous (to get back the main page)

OS X 10.10.5 (14F27), Java 8 Update 60

**Comment by AdrianoCahete** [comment]
And after clicking in link, you can't change email/password, it's just site's homepage.

@ Win 10.

**Comment by AdrianoCahete** [comment]
Similar to #10 btw

**Comment by dmxt** [comment]
Fixed, will be effective on next version.

**Comment by soyuka** [comment]
:+1: #10 is the same yes, to back to previous solution
