### ISSUE TITLE
Picture isn't showing

### ISSUE THREAD

**Issue by ElGatoSaez** [AurousGroup/Bug-Tracker#42]
Picture isn't showing, as seen in this image: 
![image](https://cloud.githubusercontent.com/assets/10396037/10412472/5a26bed0-6f5d-11e5-9229-00ab4daa8ff0.png)

**Comment by srcnalt** [comment]
I stated that here #31

**Comment by ElGatoSaez** [comment]
Sorry

**Comment by srcnalt** [comment]
:0) no probs, just search before submitting an issue.

**Comment by Codeusa** [comment]
Duplicate of #31
