### ISSUE TITLE
Can't get out of website

### ISSUE THREAD

**Issue by ElGatoSaez** [AurousGroup/Bug-Tracker#43]
As clicking on settings and then on the aurous.me link, Aurous turns into a browser and you can't get out of the webpage. 
![image](https://cloud.githubusercontent.com/assets/10396037/10412477/87fbdbf6-6f5d-11e5-9ce8-ae2d06e4af65.png)

**Comment by dmxt** [comment]
Fixed, it will be effective on next version. Thanks.
