### ISSUE TITLE
P2P? FLAC? Torrent stuff?

### ISSUE THREAD

**Issue by Radww** [AurousGroup/Bug-Tracker#53]
https://torrentfreak.com/aurous-promises-to-be-a-popcorn-time-for-music-150911/ where's the P2P? Where's the torrent stuff? Where's the flac, waw, ogg, opus, weba format? All what I see is only a grabber and only mp3 files at 320kbps bitrate.

**Comment by ramses2029** [comment]
It's an alpha release, relax...

**Comment by ElGatoSaez** [comment]
Take in care this is 0.1 Alpha

**Comment by Codeusa** [comment]
Its all there, you just didn't seem to look.
