### ISSUE TITLE
Pour preformance

### ISSUE THREAD

**Issue by duramato** [AurousGroup/Bug-Tracker#54]
Aurous seems to have a bad performace ,slow ui etc,
Im running it on windows 7 ,intel pentium dual core running at 2ghz ,3gb of ram on a 64 bit

**Comment by Codeusa** [comment]
Duplicate report, aware of animation issues and they will be fixed.

**Comment by duramato** [comment]
@Codeusa oh ok ,could you like the original issue? as i dint seem to find any...
