### ISSUE TITLE
(Widows) I can't view aurous download in the page.

### ISSUE THREAD

**Issue by moige** [AurousGroup/Bug-Tracker#59]
I'm from Venezuela, and I can't download aurous because I can't see de download button. Instead, I see the subscription button.
![fbaefce8f0c9bdae86b909f68b4b62ce](https://cloud.githubusercontent.com/assets/15069486/10413800/22875754-6f81-11e5-9cf6-135948318d16.png)

**Comment by Codeusa** [comment]
CTRL+f5
