### ISSUE TITLE
Arch Linux nothing happening

### ISSUE THREAD

**Issue by adamundercover** [AurousGroup/Bug-Tracker#66]
I've installed all the dependencies including oracle's jre, tried using both libgcrypt11 & libgcrypt15, and the 32 & 64 bit versions.

Whenever I run the app, nothing happens as seen here:
![screenshot from 2015-10-11 13-19-06](https://cloud.githubusercontent.com/assets/4150080/10414486/b264a022-701a-11e5-9d36-2f46e431a04d.png)

**Comment by adamundercover** [comment]
Its status is listed as sleeping

![java pid 16968 _026](https://cloud.githubusercontent.com/assets/4150080/10414496/2281da64-701b-11e5-9881-b623f90a5d85.png)

**Comment by hails** [comment]
Do you have `java-openjfx` installed?

**Comment by adamundercover** [comment]
Yes

**Comment by Codeusa** [comment]
See #63 and #41

**Comment by adamundercover** [comment]
Ah, thanks! I considered running it as root but seeing as the java source hasn't been released yet I wasn't too comfortable doing that. Perhaps you could change the readme file to say that it requires root

**Comment by sevaivanov** [comment]
Same on Debian Jessie. Also, running it root is still an issue.
