### ISSUE TITLE
please, dont minify your code on the git. minify it on the realease-builds..

### ISSUE THREAD

**Issue by neolectron** [AurousGroup/Bug-Tracker#71]
I think all is in the title.
we can't read your code if you minify app.js
please consider using your minifier for release-builds :smile: 
Thanks

**Comment by Codeusa** [comment]
app.js on the frontend repo is just a left over, the entire source is present 

https://github.com/AurousGroup/frontend/tree/master/app/assets/js/app

**Comment by neolectron** [comment]
i don't exacly get what you mean by "left-over",
i just started reading the source, and naturally started reading app.js,
i get confused because it was minified.. :confused: nvm,
 
And btw, you ment to let your API key (for last.fm) visible in app.js ? 
(4cb074e4b8ec*)

**Comment by Codeusa** [comment]
I left it there so others could still utilizes last.fm features while contributing. Last.fm has closed api account creation for sometime now and I figured i'd contribute that. 

app.js is not loaded by the application and I shall remove it, all .js files are loaded individually.

**Comment by neolectron** [comment]
ok, thanks , i'll close this ticket.
:)
