### ISSUE TITLE
( Linux 64, openSuSE 13.2 )Error: Could not find or load main class me.aurous.Aurous

### ISSUE THREAD

**Issue by jeisoncg** [AurousGroup/Bug-Tracker#72]
Error: Could not find or load main class me.aurous.Aurous

**Comment by neolectron** [comment]
please avoid similar/duplicate Issue, 
here's what you are looking for.
(i know you are on openSuSe and this topic is about archlinux, but the error is still the same imo)
:smile:

**Comment by jeisoncg** [comment]
Sorry, just post the Issue and continue with my work.
