### ISSUE TITLE
Arch Linux - The text is missing

### ISSUE THREAD

**Issue by DrJosepon** [AurousGroup/Bug-Tracker#73]
The program runs and I can play the songs, but there's no actual text showing in the interface.

**Comment by xzoldyck** [comment]
same here! (I use Antergos based on arch linux) I can listen the music but no text showing.

**Comment by DrJosepon** [comment]
I found a solution, I created a fork of the front end and overrided some lines of the main css.

**Comment by DrJosepon** [comment]
Here's my solution: https://github.com/DrJosepon/frontend
