### ISSUE TITLE
Add Playlist & Dropdown meni with options = Add playlist , add to ''name'' playlist 

### ISSUE THREAD

**Issue by Draxler** [AurousGroup/Bug-Tracker#90]
Win 7 64 Bit

We all noticed that Add Playlist is missing but what is also missing is Dropdown Meni with options to Add Playlist & add to ''available'' playlist. It seams this options were already implemented in earlear version.

![aurous](https://cloud.githubusercontent.com/assets/7681671/10417220/984a7d10-7033-11e5-8e43-7eaa012c306a.png)

**Comment by gregor160300** [comment]
Maybe it was just a mock up, but I noted it too, I think playlist is a necessary feature for a music player

**Comment by dmxt** [comment]
Playlist feature is coming soon.

**Comment by gregor160300** [comment]
Nice to hear that, can't wait for it and keep up the good work :)
